Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebkinzManagement.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult About()
        {
            return View();
        }
    }
}

Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using WebkinzManagement.Services;
using WebkinzManagement.Models;
using WebkinzManagement.ViewModels;
using Microsoft.AspNetCore.Authorization;

namespace WebkinzManagement.Controllers
{
    public class ProductController : Controller
    {
        private IProductRepository _tempdata;
        public ProductController(IProductRepository tempdata)
        {
            // dependency injection
            _tempdata = tempdata;
        }


        public IActionResult Index()
        {
            IndexViewModel model = new IndexViewModel(); // temp class
            model.Products = _tempdata.ReadAll();
            return View(model);
        }


        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Product obj)
        {
            if (ModelState.IsValid)
            {
                _tempdata.AddProduct(obj);
                ViewBag.Message = "Product was successfully added!";
            }
            //return RedirectToAction("Index");
            return View(obj);
        }


        public IActionResult Details(int? id)
        {
            var pro = _tempdata.GetProduct(id);
            if (pro == null)
            {
                return NotFound();
            }
            return View(pro);
        }


        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(int id)
        {
            Product obj = _tempdata.GetProduct(id);
            return View(obj);
        }
        [HttpPost]
        public IActionResult Edit(Product obj, int id)
        {
            obj.Id = id;
            if (ModelState.IsValid)
            {
                _tempdata.UpdateProduct(obj);
                ViewBag.Message = "Product was susccessfuly updated!";
            }
            return RedirectToAction("Index");
        }


        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int id)
        {
            _tempdata.DeleteProduct(id);
            return RedirectToAction("Index");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="icon" href="~/images/headerlogo.png"/>
</head>
<body class="mainbodybg">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3 mainheader">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/Images/WebkinzLogo.png"/></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between headertext">
                    <ul class="navbar-nav flex-grow-1 headertext">
                        <li class="nav-item">
                            <a class="nav-link headertext" asp-area="" asp-controller="About" asp-action="About">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link headertext" asp-area="" asp-controller="Product" asp-action="Index">Products</a>
                        </li>
                        
                    </ul>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <a class="headertext">Welcome @User.Identity.Name</a>
                    }

                    @if (User.Identity.IsAuthenticated)
                    {
                        <a class="nav-link headertext" asp-action="Logout" asp-controller="Account">Logout</a>
                    }
                    else
                    {
                        <a class="nav-link headertext" asp-action="Login" asp-controller="Account">Login</a>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container maintext">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WebkinzManagement - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_LayoutAccount.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="icon" href="~/images/headerlogo.png"/>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3 accountheader">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/Images/WebkinzLogo.png"/></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @if (User.Identity.IsAuthenticated)
                {
                    <a class="headertext">Welcome @User.Identity.Name</a>
                }

                @if (User.Identity.IsAuthenticated)
                {
                    <a class="nav-link headertext" asp-action="Logout" asp-controller="Account">Logout</a>
                }
                else
                {
                    <a class="nav-link headertext" asp-action="Login" asp-controller="Account">Login</a>
                }
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WebkinzManagement - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_LayoutProduct.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="icon" href="~/images/headerlogo.png"/>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3 productheader">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/Images/WebkinzLogo.png"/></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @if (User.Identity.IsAuthenticated)
                {
                    <a class="headertext">Welcome @User.Identity.Name</a>
                }

                @if (User.Identity.IsAuthenticated)
                {
                    <a class="nav-link headertext" asp-action="Logout" asp-controller="Account">Logout</a>
                }
                else
                {
                    <a class="nav-link headertext" asp-action="Login" asp-controller="Account">Login</a>
                }
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WebkinzManagement - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>